# Generated by Django 5.0.7 on 2024-09-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('salesman', 'Salesman'), ('delivery', 'Delivery')], db_index=True, default='customer', max_length=50, null=True, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_user_role_6c06b1_idx'),
        ),
    ]
