# Generated by Django 5.0.7 on 2024-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchase Date')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
