# Generated by Django 5.0.7 on 2024-09-16 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='products.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_sales_custome_b24b56_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['product'], name='sales_sales_product_ce9809_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['sale_date'], name='sales_sales_sale_da_7b8105_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='quantity_gte_1'),
        ),
    ]
